# Generated by Django 5.2 on 2025-04-09 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_project_trackingsession_total_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='tracking_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.trackingsession'),
        ),
    ]
