# Generated by Django 5.2 on 2025-04-09 05:46

import monitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_screenshot_tracking_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(upload_to=monitor.models.screenshot_upload_path),
        ),
    ]
